### ISSUE TITLE
[Issue] cannot create a new store

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#492] opened 2022-01-13 04:37 UTC
**Describe the bug**
No store can be created

**To Reproduce**
When going to create a store, the error appears when putting save

**Expected behavior**
I should create the store

**Screenshots**
![20220113_012916](https://user-images.githubusercontent.com/80654041/149266776-25274652-ed94-4bac-8552-8b0af45e5e8c.jpg)

![Captura de Pantalla 2022-01-13 a la(s) 01 42 27](https://user-images.githubusercontent.com/80654041/149267240-118c91ed-7a60-4af9-8b36-191ad537aa98.png)

![Captura de Pantalla 2022-01-13 a la(s) 01 43 01](https://user-images.githubusercontent.com/80654041/149267256-e3041b99-939b-4c52-9be8-214e9bef7e14.png)

**Environment:**
 - NexoPOS 4.x Version: [e.g. 4.6.9]
 - Premium Extensions: [e.g Nexo Print Adapter (4.6.2), Gastro (4.6.2), Bulk Importer (4.6.0], Sales Commissions (4.6.0), MultiStore (4.6.6), Pin Login (4.6.0)

**Comment by Blair2004** [comment] 2022-01-25 20:43
Hi,
The issue is fixed with multistore 4.6.9

**Closed by Blair2004** 2022-01-25 20:43 UTC
Labels: bug
