### ISSUE TITLE
Issue With Cash Flow Report

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#427] opened 2021-12-28 09:37 UTC
I made an order with 25 QR (2 items one with 15QR and the other with 10QR) and the payment is done (payment account is Talabat).
then i make order refund for all products (customer didnt receive the order). all reports are shown sale is zero becasue we refunded the 25 QR which is correct except the cash flow report shown the sales 40 QR instead of 25 QR. while observing the database it is shown an order with 15 QR which i didnt make with the same order number for 25 QR order. this 15 QR order is only reflecting in the cash flow report.
kindly see the video:

https://www.youtube.com/watch?v=d6yui5YxwVc

Also, the Cash Register in and out is dublicated in the cash flow report, kindly see the following screen shoot
 
![2 Cash Register in and out in Cash Flow Report](https://user-images.githubusercontent.com/87772530/147552870-9d2fc44a-5767-4fdc-a211-c3874c4dcefe.PNG)

Nexo POS Version: 4.6.8
Platform: Laragon on Windows 10 64 bit

**Comment by Blair2004** [comment] 2022-01-10 16:20
We've made some adjustment for 4.6.9 regarding the cash flow report. Can you give another shot to it ?
It's on the actual branch https://github.com/Blair2004/NexoPOS-4x/tree/v4.6.x.

We've removed the cash flow for the cash register. We don't believe it's necessary as every cash opening will be recorded and cash closing, while those will somehow be reflected on the sales as well. We believe the cash register will duplicate earning and therefore, we just only kept the sales and refunds (for the transaction where the sales are involved).

If the issue is not fixed, feel free to reopen the issue.

Let us know.

**Closed by Blair2004** 2022-01-10 16:20 UTC
