### ISSUE TITLE
Print a receipt showing amout due while sending order to the kitchen

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS-4x#564] opened 2022-02-09 12:05 UTC
**Describe the bug**
When a kitchen order is made and sent to the kitchen a KOT (Kitchen Order Ticket) is printed, the waiter the has to manually search for that order to print the customer bill this is time wasting for a busy restaurant, to save time we need to automatically print the customer bill immediately after the KOT, this can be made optional for those restaurants who might not require the automated printing of customer bill so we can have enable / disable button. 

**To Reproduce**
send an order to the kitchen
print the customer bill

**Expected behavior**
When waiter sends an order to the kitchen, a customer bill should also be printed automatically, so we have two printed documents the KOT (Kitchen Order Ticket) and the Customer Bill

**Screenshots**

**Environment:**
 - NexoPOS 4.6.11
 - Premium Extensions: [ Nexo Print Adapter (4.6.2), Gastro (4.6.2)]

**Comment by Blair2004** [comment] 2022-02-09 16:09
We'll test if it's not the case with the actual system. We'll update this issue accordingly.

**Comment by Blair2004** [comment] 2022-02-24 08:08
We're ready to have a remote session for checking further this. Let us know on WhatsApp.

**Comment by Blair2004** [comment] 2022-04-11 10:15
We've not been able to understand and process this issue so far. maybe due to lack of details that would have helped us understanding this. We closing this for now, but feel free to create a new issue that provide more details on how to reproduce this concern.

Thanks.

**Closed by Blair2004** 2022-04-11 10:15 UTC
