### ISSUE TITLE
Cash Register closing balance should not always match with the system

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS-4x#577] opened 2022-02-22 05:09 UTC
**Describe the bug**
While using cash register, the system has its own expected balance at any given time, when you want to close the register it shows you the balance then the user is expected to enter the actual or physical cash at hand, if the user inputs amount that is different from the system balance the POS will show an error and you have to input the exact amount it shows as balance.

 
![Cash register expected balance](https://user-images.githubusercontent.com/13999977/155065525-5667fbcf-0ecf-4489-8cc9-4efe8f75bd40.png)

This is wrong, the system should accept the input amount, and calculate the difference, if the input amount is less than expected balance that is a short and if the input amount is more than expected balance that is an excess, the cash register report should show this short (Positive amount with +) and /or excess (Negative amount with -) in its report.

**To Reproduce**
Open a new register
Make a sale
Close the register
Input amount that is less or more than the balance
confirm

**Expected behavior**
The system should accept the amount, and calculate the difference, if the input amount is less than expected balance that is a short and if the input amount is more than expected balance that is an excess, the cash register report should show this short (Positive amount with +) and /or excess (Negative amount with -) in its report.

**Screenshots**

**Environment:**
 - NexoPOS 4.6.11

**Comment by Blair2004** [comment] 2022-02-22 16:15
Possible Duplicate of https://github.com/Blair2004/NexoPOS-4x/issues/551

**Closed** 2022-03-28 11:01 UTC
