### ISSUE TITLE
[Issue] "dine in", "pick up", and "deliver" options not displying

### ISSUE THREAD

**Issue by jintsai12** [Blair2004/NexoPOS-4x#610] opened 2022-03-19 15:47 UTC
**Describe the bug**
Kitchen receipt doesn't display "dine in", "pick up", and "deliver" options by using Nexo server print

**To Reproduce**
1. Click "To kitchen"
2. Using nexo server print
3. the kitchen receipt doesn't display "dine in", "pick up", and "deliver"
4. The chef doesn't know if this order is for dine in or pickup

**Expected behavior**
kitchen receipt should display "dine in", "pick up", and "deliver", so the chef can understand better for preparing the meal.

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.x]
 - Premium Extensions: [e.g Nexo Print Adapter (4.6.x), Gastro (4.6.x)]

**Comment by Blair2004** [comment] 2022-04-11 09:34
![image](https://user-images.githubusercontent.com/5265663/162710324-aed011ea-1bfc-409a-a271-0b48f78cbf58.png)
We believe the option is added since the version 4.6.7
We'll perform a test and close this if it's confirmed

**Comment by Blair2004** [comment] 2022-04-11 10:16
We're closing this issue for now, but feel free to reopen it if that issue persists.

**Closed by Blair2004** 2022-04-11 10:16 UTC
