### ISSUE TITLE
[Issue] password not encrypted

### ISSUE THREAD

**Issue by m2fik** [Blair2004/NexoPOS-4x#463] opened 2022-01-03 19:22 UTC
New user was saved with not encrypted password in Mysql and after search in coding I see that filterPostInputs( $inputs ) in UserCrud is not called from CrudService and all Hook::filter are not working.

**Environment:**
 - NexoPOS 4.6.7 & 4.6.8
 - Premium Extensions: Gastro v4.6.2

**Comment by Blair2004** [comment] 2022-01-03 20:19
Hi, Thank for reporting. This issue should have been fixed with 4.6.8. ill test with that version

**Comment by m2fik** [comment] 2022-01-06 13:54
Hi,
yes it works 4.6.8 and I see that you add 
`if ( method_exists( $resource, 'filterPostInputs' ) && ! $isEditing ) {
            $inputs    =   $resource->filterPostInputs( $inputs, null );
        }`
`if ( method_exists( $resource, 'filterPutInputs' ) && $isEditing ) {
            $inputs    =   $resource->filterPutInputs( $inputs, $entry );
        }`
why this code 
`
$inputs     =   Hook::filter( 
            get_class( $resource ) . $isEditing ? '@filterPutInputs' : '@filterPostInputs', 
            $inputs
        );
`
is there and there is no filter in boot.
better this
`
$inputs = \App::call(get_class($resource) . ($isEditing ? '@filterPutInputs' : '@filterPostInputs' ), ['inputs' => $inputs]);
`

**Comment by Blair2004** [comment] 2022-01-06 14:40
That issue is solved on 4.6.8 have you tried ?

**Comment by m2fik** [comment] 2022-01-06 14:58
Hi,
I say yes and I asked a question about a coding? Why a code still there and there in no hook filter in boot for it?

**Comment by Blair2004** [comment] 2022-01-06 19:30
The code will ensure any module can mutate the filter value. Previously on the Crud instance was able to do so.

**Comment by m2fik** [comment] 2022-01-07 04:17
Hi, 
here is in doc from tormjens/eventy
$value = Eventy::filter('my.hook', 'awesome');
If no listeners are attached to this hook, the filter would simply return 'awesome'.
and in your code 
`$inputs = Hook::filter( get_class( $resource ) . $isEditing ? '@filterPutInputs' : '@filterPostInputs', $inputs );`
there is no listener and this the same $inputs = $inputs ?????.
and this ` get_class( $resource ) . $isEditing ? '@filterPutInputs' : '@filterPostInputs'` will always give @filterPostInputs because `get_class( $resource ) . $isEditing` will never give true
correct is with parentheses `get_class( $resource ) .( $isEditing ? '@filterPutInputs' : '@filterPostInputs)'` and it gives App\Crud\UserCrud@filterPutInputs or App\Crud\UserCrud@filterPostInputs when you use with User and  with roles it gives App\Crud\RolesCrud@filterPutInputs or App\Crud\RolesCrud@filterPostInputs.......

And there are a lot of Hook::filter with no listener in your coding that takes resources.

**Comment by Blair2004** [comment] 2022-01-07 05:37
as i said, this is made to ensure the values can be mutated by modules. That are measures taken to ensure the flexibility of the code and a filter that doesn't have listener don't really consume resources. Take a look at WordPress core and search for the filter you'll see there is a bunch of them and not all are used but available so any plugin can hook in.

I believe the issue is resolved not, for any discussion regarding the performance consider creating a thread on the "[Discussion](https://github.com/Blair2004/NexoPOS-4x/discussions)" Tab.

**Closed by Blair2004** 2022-01-07 05:37 UTC

**Comment by m2fik** [comment] 2022-01-07 11:00
ok, and sorry
