### ISSUE TITLE
[Issue] There are problems that need to be solved very urgently, please help me.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#797] opened 2022-05-24 20:28 UTC
1. I choose the kitchen printer, but when I enter the order, the receipt does not come out of the printer.
![1](https://user-images.githubusercontent.com/102427740/170125756-15f2993f-b2f8-4341-9b2c-7ec86dea0c42.png)

2. nexo print server does not support Turkish characters
![7d777019-71d9-46f4-8f2c-0491400d8e1f](https://user-images.githubusercontent.com/102427740/170126028-56d12fb0-4b5a-46ca-8662-d06391ed0743.jpg)

**Comment by Blair2004** [comment] 2022-05-25 05:19
Hi,
Thank you for reporting. We'll proceed the test with that.
Consider letting us know the printer you're using.

**Comment by lim10soft** [comment] 2022-05-25 12:23
Hello, I tried with many printer models, they all have the same problem. When printing from normal web, there is no problem. When printing from nexo print server nps adapter, there is a problem.

UNSUPPORTED CHARACTERS.   Ü=U;ü=u;Ğ=G;ğ=g;Ş=S;ş=s;İ=I;i=ı;Ö=O;ö=o;Ç=C;ç=c=₺

printer models I tested: wınpal wp23ow, Afanda 892E

In another problem, although I selected the kitchen printer, the plug does not print to the kitchen.


I can't use these problems are urgent.

**Comment by Blair2004** [comment] 2022-05-26 07:43
Hi, Let's connect privately for checking why the kitchen doesn't work.
However regarding the printing compatibility we'll need further time to check that.

**Comment by lim10soft** [comment] 2022-05-26 09:51
so how do i get the link? are you using anydesk via e-mail?



26 May 2022 Per 10:43 tarihinde Blair Jersyer ***@***.***>
şunu yazdı:

**Comment by Blair2004** [comment] 2022-05-26 12:21
Hi, please send your AnyDesk ID through contact@nexopos.com

**Comment by lim10soft** [comment] 2022-05-26 12:28
Hello, I have shared the information, I am waiting for you to connect.

**Comment by lim10soft** [comment] 2022-05-28 16:16
Hello, I have a new solution to the Turkish character problem in the nexo print server.

Ü=U;ü=u;Ğ=G;ğ=g;Ş=S;ş=s;İ=I;i=ı;Ö=O;ö=o;Ç=C;ç=c=₺

the problem is resolved if it automatically converts these characters to normal characters when printing. It is not important to write Turkish characters on the receipt As I mentioned above, when printing, for example, if the letter ş is S, the problem is solved.

**Comment by Blair2004** [comment] 2022-05-31 10:32
We're working on a solution for such characters.
This will be closed as a similar issue already exists

duplicate of #720

**Closed by Blair2004** 2022-05-31 10:32 UTC
