### ISSUE TITLE
[Issue] No products added...

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#506] opened 2022-01-15 12:45 UTC
I tried to open on hold order , I got this screen : No products added

**To Reproduce**
1. Go to 'orders'
2. Click on 'on hold'
3. Scroll down to 'open
![Screenshot 8](https://user-images.githubusercontent.com/22215705/149622184-accc159d-43b6-4233-b34e-44d607b26120.png)
![Screenshot (4)](https://user-images.githubusercontent.com/22215705/149622186-6434631f-3dae-4f16-8db3-2a2b9507966f.png)
'

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.10
 - Premium Extensions: Gastro (4.6.2)

**Comment by Blair2004** [comment] 2022-01-15 16:16
Duplicate of https://github.com/Blair2004/NexoPOS-4x/issues/482

**Closed by Blair2004** 2022-01-15 16:16 UTC
Labels: bug
