### ISSUE TITLE
Deleted all orders, total sales still showing the value instead of setting back to 0

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#109] opened 2020-12-20 18:30 UTC
![image](https://user-images.githubusercontent.com/16180446/102721222-7c6fe380-4334-11eb-98e8-0bafd8dc8aa7.png)

Does the same with expenses

**Comment by Blair2004** [comment] 2020-12-21 23:37
Have you successfully set up the queue and the CRON?
What is the environment you're using NexoPOS right now?

**Comment by Cyaaaaaaaaan** [comment] 2020-12-22 15:47
> Have you successfully set up the queue and the CRON?
> What is the environment you're using NexoPOS right now?

Yes, it did reset back the value but if I look in annual reports, sales are still there. And also why does the jobs do not start on their own, is it supposed to behave that way?

**Comment by Blair2004** [comment] 2020-12-22 17:17
You need to setup the jobs for it to run.

**Comment by Cyaaaaaaaaan** [comment] 2020-12-23 04:23
The sales came back after a day? 🤷🏻‍♂️

**Comment by Blair2004** [comment] 2020-12-26 19:10
Unable to reproduce with a setup that has Cron and Queue correctly setup. Please make sure NexoPOS 4.x doesn't throw any notification about Queue not correctly setup. I'm closing for now.

**Closed by Blair2004** 2020-12-26 19:10 UTC

**Comment by Cyaaaaaaaaan** [comment] 2020-12-28 15:04
How can I setup the Cron and Queue? I tried running `php artisan schedule:run` but it's not working. It only says `no scheduled commands are ready to run`

**Comment by Blair2004** [comment] 2020-12-28 15:33
on development you can either run : 
```
php artisan schedule:run
php artisan queue:work
```
But sadly you'll need to run that before using the app. Unless you're able to create scheduled tasks (on Windows) that will perform both CLI queries.

Alternatively, you should use WSL (Windows Subsystem for Linux) to install NexoPOS. FYI, WLS makes you run Linux distros on Windows and that's should be natively supported on Windows.

https://dev.to/manuelojeda/setup-a-php-dev-enviroment-with-laravel-valet-and-wsl-1pp6

**Comment by zedreez** [comment] 2022-02-04 18:06
so I should run `php artisan schedule:run` before I setup the nexopos installation?
